The Coffee-overdose version.
Supports the following `make' options: -n, -k, -S, -v, -h, --help, --version
Other options are ignored (but only single-dash options for now).

Added cvs-build target, that will build the ChangeLog and launch
a dpkg-buildpackage,

Now honours DEB_BUILD_OPTIONS=nostrip! In this case, the shoop modules
(and shoop itself) won't be compiled with utils/shell-stripper.

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -1,11 +1,19 @@
-#! /bin/sh -e
+#! /bin/sh
 ## debian/rules for SHOOP
 ## by Gergely Nagy <algernon@debian.org>
+##
+## Trapped in time
+## A miracle of hope and change
+## A swirling mass, no mercy now
+## If the truth hurts prepare for pain
+## ...Do you think we're forever ?
+##
+##	- Anathema: Eternity Part I
 
 # exports
 export SHOOPPATH=${PWD}:${PWD}/modules
 export SHOOPMOD=${PWD}/modules
-export DH_COMPAT=3
+export DH_COMPAT=2
 
 # #include <shoop>
 . ${PWD}/shoop.sh
@@ -14,14 +22,25 @@ export DH_COMPAT=3
 OBJECT . new DEBIAN
 
 DEBIAN . MAKE_LEVEL =q 0
+DEBIAN . dry_run =q no
+DEBIAN . verbose =q yes
+DEBIAN . keep_going =q no
+DEBIAN . DPKG_BUILDPACKAGE =q ${DPKG_BUILDPACKAGE:-dpkg-buildpackage}
+DEBIAN . INSTALL_OPTIONS =q ""
 
 # core methods
-DEBIAN . header : 'echo "==> [`eval $THIS . MAKE_LEVEL`] Making $@" 1>&2
-	$THIS . MAKE_LEVEL =q `expr \`eval $THIS . MAKE_LEVEL\` + 1`'
-DEBIAN . done : '$THIS . MAKE_LEVEL =q `expr \`eval $THIS . MAKE_LEVEL\` - 1`
-	echo "<== [`eval $THIS . MAKE_LEVEL`] Finished $@" 1>&2'
-DEBIAN . do : 'echo $@
-	eval $@'
+DEBIAN . do_header : 'echo "==> [$($THIS . MAKE_LEVEL)] Making $@" 1>&2
+	$THIS . MAKE_LEVEL =q $(expr $($THIS . MAKE_LEVEL) + 1)'
+DEBIAN . do_done : '$THIS . MAKE_LEVEL =q $(expr $($THIS . MAKE_LEVEL) - 1)
+	echo "<== [$($THIS . MAKE_LEVEL)] Finished $@" 1>&2'
+DEBIAN . do : 'if test "x$($THIS . verbose)" != "xno"; then echo $@; fi
+	if test "x$($THIS . dry_run)" = "xno"; then eval $@; fi'
+DEBIAN . header : 'if test "x$($THIS . verbose)" != "xno"; then
+		$THIS . do_header $@
+	fi'
+DEBIAN . done : 'if test "x$($THIS . verbose)" != "xno"; then
+		$THIS . do_done $@
+	fi'
 
 # These do the Real Job
 DEBIAN . do_build : 'test -f build-stamp || $THIS . build_stamp'
@@ -31,14 +50,19 @@ DEBIAN . do_build_stamp : '$THIS . do dh_testdir
 DEBIAN . do_clean : '$THIS . do dh_testdir
 	$THIS . do dh_testroot
 	$THIS . do rm -f build-stamp docs/modules.txt docs/modules.pod
+# Back up the ChangeLog
+	mv ChangeLog ChangeLog.backup
+# Clean up!
 	$THIS . do "make clean || true"
+# Copy the ChangeLog back
+	mv ChangeLog.backup ChangeLog
 	$THIS . do dh_clean'
 DEBIAN . do_install : '$THIS . build
 	$THIS . do dh_testdir
 	$THIS . do dh_testroot
 	$THIS . do dh_clean -k
 	$THIS . do dh_installdirs
-	$THIS . do make install
+	$THIS . do make install $($THIS . INSTALL_OPTIONS)
 	$THIS . do rm -f debian/shoop/usr/share/doc/shoop/COPYING \
 			 debian/shoop/usr/share/doc/shoop/COPYING.gz
 	$THIS . do mv debian/shoop/usr/share/shoop/modules \
@@ -50,6 +74,7 @@ DEBIAN . do_install : '$THIS . build
 	$THIS . do rm -rf debian/shoop/usr/share/doc/shoop/examples
 	$THIS . do ln -sf shoop debian/shoop-dev/usr/share/doc/shoop-dev
 	$THIS . do ln -sf shoop debian/shoop-modules/usr/share/doc/shoop-modules
+# I have to use ugly IFS magic here, otherwise things would fail miserably
 	SAVE_IFS="$IFS"
 	GOOD_IFS=" 	
 "
@@ -87,6 +112,9 @@ DEBIAN . do_binary_arch : ''
 DEBIAN . do_binary_indep : '$THIS . packages'
 DEBIAN . do_binary : '$THIS . binary_arch
 	$THIS . binary_indep'
+DEBIAN . do_cvs_build : '# Oh boy, oh boy!
+	$THIS . do make ChangeLog
+	$THIS . do $($THIS . DPKG_BUILDPACKAGE)'
 
 # Wrapper function that calls header & done too
 DEBIAN . do_func : '$THIS . header $LASTMETH
@@ -101,24 +129,88 @@ DEBIAN . packages : DEBIAN . do_func
 DEBIAN . binary_arch : DEBIAN . do_func
 DEBIAN . binary_indep : DEBIAN . do_func
 DEBIAN . binary : DEBIAN . do_func
+DEBIAN . cvs_build : DEBIAN . do_func
 
 # void main ( whatever )
-DEBIAN . debian : '$THIS . header debian
-	for opt in $@
+DEBIAN . debian : '# Go Johny, go! Go Johny, go go go!
+	while test $# -gt 0
 	do
+		opt=$1
+		shift
+
 		case $opt in
-			build|build-stamp|clean|install|packages|binary-arch|binary-indep|binary)
-				method=`echo $opt | sed -e "s,\-,_,g"`
-				DEBIAN . $method
+			build|build-stamp|clean|install|packages|binary-arch|binary-indep|binary|cvs-build)
+				method=$(echo $opt | sed -e "s,\-,_,g")
+				$THIS . TODO .=q $method
+				;;
+			DEB_BUILD_OPTIONS=*nostrip*)
+				$THIS . INSTALL_OPTIONS .=q "strip_comment_space=/bin/cat"
 				;;
 			DEB_*=*)
 				# These are useless for us
+				;;
+			-*b*|-*m*|-*d*|-*e*|-*i*|-*p*|-*q*|-*r*|-*t*|-*w*|-*C|-*f|-*I|-*o|-*W|-*j*|-*k*|-*s*|-*S-|-*n*|-*l*)
+				# Ignored, handled later
+				;;
+			-*)
+				echo "*** Unsupported option: $opt"
+				exit 1
 				;;
 			*)
 				echo "*** Unsupported target: $opt"
 				exit 1
 				;;
 		esac
+		case $opt in
+			-*b*|-*m*|-*d*|-*e*|-*i*|-*p*|-*q*|-*r*|-*t*|-*w*)
+				# Ignored for GNU Make compatibility
+				;;
+		esac
+		case $opt in
+			-*C|-*f|-*I|-*o|-*W|-*l)
+				# Ignored (with arguments) for GNU Make compatibility
+				shift
+				;;
+		esac
+		case $opt in
+			-*j*)
+				# This is not implemented yet
+				;;
+		esac
+		case $opt in
+			-*k*)
+				$THIS . keep_going =q yes
+				;;
+		esac
+		case $opt in
+			-*S*)
+				$THIS . keep_going =q no
+				;;
+		esac
+		case $opt in
+			-*n*)
+				$THIS . dry_run =q yes
+				;;
+		esac
+		case $opt in
+			-*s*)
+				$THIS . verbose =q no
+				;;
+		esac
+		case $opt in
+			-*v*)
+				$ THIS . version
+				exit 0
+				;;
+		esac
+	done
+	$THIS . header debian
+	if test "x$($THIS . keep_going)" = "xno"; then
+		set -e
+	fi
+	# FIXME : $THIS . TODO empty => print warning
+	for rule in $($THIS . TODO); do
+		$THIS . $rule
 	done
 	$THIS . done debian'
 
